services:
  fs-mock:
    image: nikhil/fs-mock:latest
    container_name: fs-mock
    ports:
      - "30233:8080"

  fs-service:
    image: nikhil/fs-service
    container_name: fs-service
    ports:
      - "30093:8080"

  fs-warehouse:
    image: nikhil/fs-warehouse
    container_name: fs-warehouse
    ports:
      - "30533:8080"