openapi: 3.0.3
info:
  title: FlightScanner
  description: A flight scanning service demo application
  version: 0.1.0
servers:
  - url: https://localhost:8050
tags:
  - name: flight
    description: Search for flights from multiple airlines

paths:
  /flights:
    get:
      tags:
        - flight
      summary: Get all flight options for source to destination
      description: Fetch flight details from airlines
      operationId: getFlights
      parameters:
        - in: query
          name: source
          schema:
            type: string
          description: Airport code of the source city e.g. BOM for Mumbai
        - in: query
          name: destination
          schema:
            type: string
          description: Airport code of the destination city e.g. FRA for Frankfurt
        - in: query
          name: travelDate
          schema:
            type: string
          description: Date in DD-MM-YYYY format
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Flight'
        '400':
          description: Invalid input supplied
        '404':
          description: Flight not found
        '422':
          description: Validation exception
      security:
        - flights_auth:
            - read:flights

components:
  schemas:
    Flight:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 10
        source:
          type: string
          example: BOM
        destination:
          type: string
          example: FRA
        departure:
          type: string
          format: date-time
        arrival:
          type: string
          format: date-time
  securitySchemes:
    flights_auth:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: https://localhost:8050/oauth/authorize
          scopes:
            read:flights: read flight details
    api_key:
      type: apiKey
      name: api_key
      in: header