openapi: 3.0.3
info:
  title: KLM Offers API
  description: A mock providing offer bids
  version: 0.1.0
servers:
  - url: https://localhost:30133/mock/v1/klm
tags:
  - name: offer
    description: Price offer and related details
  - name: flightDetails
    description: required details to get an offer bid

paths:
  /klm/offers:
    post:
      tags:
        - offer
      summary: Get lowest fare for provided flight details
      operationId: offer
      requestBody:
        description: Post flight details to get a bid for pricing
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/FlightDetails'
        required: true
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Offer'

components:
  schemas:
    Offer:
      type: object
      properties:
        offerPrice:
          type: number
          format: double
          description: Lowest offered price in Euros
          example: 520.42

    FlightDetails:
      type: object
      properties:
        origin:
          type: string
          description: Airport code of starting point
          example: FRA
        destination:
          type: string
          description: Airport code of destination point
          example: BOM
        travelDate:
          format: date
          example: 2024-01-01